services:
  pakuchibot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pakuchibot
    volumes:
      - ./data:/PakuchiBot/data
      - ./config:/PakuchiBot/config
      - ./assets:/PakuchiBot/assets
    networks:
      - pakuchibot-network
    restart: unless-stopped

  pakuchibot-watchtower:
    image: containrrr/watchtower
    container_name: pakuchibot-watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --stop-timeout 60s
    networks:
      - pakuchibot-network

networks:
  pakuchibot-network:
    driver: bridge
