services:
  pakuchibot:
    image: weatheringocean/pakuchibot:latest
    container_name: pakuchibot
    volumes:
      - ./data:/PakuchiBot/data
      - ./config:/PakuchiBot/config
      - ./assets:/PakuchiBot/assets
    environment:
      - TZ=Asia/Shanghai
    networks:
      - pakuchibot-network
    restart: unless-stopped

  pakuchibot-watchtower:
    image: containrrr/watchtower
    container_name: pakuchibot-watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Asia/Shanghai
    command: --interval 30 --stop-timeout 60s
    networks:
      - pakuchibot-network

networks:
  pakuchibot-network:
    driver: bridge
