services:
  pakuchibot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pakuchibot
    volumes:
      - /data:/PakuchiBot/data
      - /config:/PakuchiBot/config
      - /assets:/PakuchiBot/assets
    networks:
      - pakuchibot-network
    restart: unless-stopped

networks:
  pakuchibot-network:
    driver: bridge
