# OneBot连接配置
connection:
  # WebSocket服务器地址
  ws_address: "ws://127.0.0.1:6700"
  # 访问令牌（可选）
  access_token: ""

# 机器人设置
bot:
  # 机器人QQ号
  self_id: 123456789
  # 命令前缀
  command_prefix: "/"
  # 调试模式
  debug: false
  # 日志级别 (trace, debug, info, warn, error, fatal, panic)
  log_level: "info"
  # 机器人昵称
  nicknames: ["bot", "机器人"]
  # 超级用户列表
  super_users: [123456789]

# 存储设置
storage:
  # 数据库文件路径
  db_path: "~/.zerobot/data.db"
  encryption_key: "your-32-byte-encryption-key-here!!" # 32字节的加密密钥

scheduler:
    # 签到检查间隔（秒）
    check_interval: 300
    # 最大重试次数
    max_retries: 3

# GitHub通知设置
github:
  # 是否启用GitHub通知功能
  enabled: false
  # 检查间隔（分钟）
  interval: 15
  # GitHub API令牌（可选，使用令牌可以增加API速率限制）
  token: ""
  # 监控的仓库列表
  repositories:
    # 仓库示例1
    - owner: "wdvxdr1123"
      name: "ZeroBot"
      monitor_type: ["commit", "release"]
    # 仓库示例2
    - owner: "FloatTech"
      name: "zbputils"
      monitor_type: ["release", "issue"]
  # 通知目标列表
  notify_targets:
    # 群组通知示例 - 订阅所有仓库
    - type: "group"
      id: 123456789
      # repos字段为空表示接收所有仓库的通知
    # 群组通知示例 - 只订阅特定仓库
    - type: "group"
      id: 987654321
      repos: ["wdvxdr1123/ZeroBot", "FloatTech/zbputils"]
    # 私聊通知示例 - 只订阅特定仓库
    - type: "private"
      id: 987654321
      repos: ["wdvxdr1123/ZeroBot"]

# 人类模拟设置
humanlike:
  # 是否启用人类模拟功能
  enabled: true
  # LLM API配置
  llm:
    api_key: "your-api-key-here"
    base_url: "https://api.openai.com/v1"
    model: "gpt-3.5-turbo"
    temperature: 0.7
    max_tokens: 800
  # Vision模型配置
  vision:
    enabled: true
    model: "gpt-4-vision-preview"
    temperature: 0.7
    max_tokens: 300
    # 以下配置如与llm的配置相同可留空
    base_url: "https://api.openai.com/v1"
    api_key: "your-vision-api-key-here"
  behavior:
    # 最小打字速度（字符/秒）
    min_typing_speed: 3
    # 最大打字速度（字符/秒）
    max_typing_speed: 8
    # 是否启用群组白名单
    enable_group_whitelist: false
    # 群组ID白名单，仅在启用白名单且在这些群组中时才启用人类模拟功能
    group_whitelist: []
