name: Docker Image CI Amd64

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Get commit SHA
        run: echo "SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag weatheringocean/pakuchibot:latest

      - name: Push to DockerHub
        run: |
          docker tag weatheringocean/pakuchibot:latest weatheringocean/pakuchibot:${{ env.SHA }}
          docker push weatheringocean/pakuchibot:latest
          docker push weatheringocean/pakuchibot:${{ env.SHA }}
